POST http://localhost:3000/reports
content-type: application/json

{
    "make": "toyota",
    "model": "camry",
    "year": 1995,
    "mileage": 100000,
    "lng": 0,
    "lat": 0,
    "price": 707
}

### Approve existing report
PATCH http://localhost:3000/reports/7
content-type: application/json

{
    "approved": true
}